version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: lsu_pilot/Dockerfile
    container_name: chat_app
    ports:
      - "8080:8080"
      - "5678:5678"
    depends_on:
      - redis
    env_file:
      - ./.env
    environment:
      DEBUG: ${DEBUG:-0}
    command: ["./entrypoint.sh"]

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery_worker:
    build:
      context: .
      dockerfile: workers/Dockerfile
    container_name: celery_worker
    ports:
      - "5679:5678"
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - ./.env
    environment:
      DEBUG_WORKER: ${DEBUG_WORKER:-0}
    command: ["./entrypoint.sh"]

  flower:
    build:
      context: .
      dockerfile: workers/Dockerfile
    container_name: flower
    volumes:
      - .:/app
    command: celery -A workers.task_handlers flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - celery_worker
      - rabbitmq
      - redis
    env_file:
      - ./.env

volumes:
  redis_data: