version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: lsu_pilot/Dockerfile
    container_name: chat_app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - ./.env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery_worker:
    build:
      context: .
      dockerfile: lsu_pilot/Dockerfile
    container_name: celery_worker
    volumes:
      - .:/app
    command: celery -A lsu_pilot worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - ./.env

  flower:
    build:
      context: .
      dockerfile: lsu_pilot/Dockerfile
    container_name: flower
    volumes:
      - .:/app
    command: celery -A lsu_pilot flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - celery_worker
      - rabbitmq
      - redis
    env_file:
      - ./.env

volumes:
  redis_data: